### ISSUE TITLE
Spaces in paper names not supported?

### ISSUE THREAD

**Issue by mconley99** [alexras/libris#2]
If I create a paper title with spaces in it, my editor goes crazy and tries to edit each word as a separate path.  For example

```
paper-pile add -n "Building Flexible, Fault-Tolerant Flash-based Storage Systems" PATH
```

succeeds and stores the paper properly. However

```
paper-pile edit_metadata "Building Flexible, Fault-Tolerant Flash-based Storage Systems"
```

Causes my editor to bring up several files: ~/Systems/metadata.yaml, ~/Storage, ~/Flash-based, ~/Fault-tolerant, ~/Flexible, and ~/Dropbox/Papers/Building

**Comment by mconley99** [comment]
It looks like I can just put the title of the paper in the metadata, and use some other identifying information for the paper name such as "Author_Venue_Year".  No need for any changes, but I'll leave this up so there's a record at least.

**Comment by alexras** [comment]
Ah, I see. The paper's name wasn't really meant to correspond to its title at all; it was mostly meant to just be a primary key for the paper itself. That said, I'll make sure that spaces are automatically converted into underscores or something to prevent this problem from recurring.
