### ISSUE TITLE
[Feature] Auto-completion of paper names

### ISSUE THREAD

**Issue by mconley99** [alexras/libris#4]
I'm pretty sure this amounts to a bash script like the one for git, but it would be awesome if the paper-pile command line could auto-complete paper names.  For example I could type "paper-pile edit_notes Ag[TAB]" and it would auto complete to "Aggarwal_ACM_88"

**Comment by alexras** [comment]
It does, if you're using bash and have bash_completion installed. Just add 

``` bash
# Add paper-pile bash completion
PAPER_PILE_BASH_COMPLETION="$HOME/src/paper-pile.git/bash_completion"
if test -f ${PAPER_PILE_BASH_COMPLETION}
then
    source ${PAPER_PILE_BASH_COMPLETION}
fi
```

to your `~/.bashrc`.

I'll add this to the README as well.
